#!/bin/sh

CERT_SRC="/var/db/acme/certs"

CERT_DST_ROOT="/var/db/certs-for-rsync"
CERT_DST_CERTS="${CERT_DST_ROOT}/certs"

TMP="${CERT_DST_ROOT}/tmp"

BASENAME="/usr/bin/basename"
CP="/bin/cp"
FIND="/usr/bin/find"
GREP="/usr/bin/grep"
MKDIR="/bin/mkdir"
MV="/bin/mv"
RMDIR="/bin/rmdir"
SYSRC="/usr/sbin/sysrc"

# find directories modified in the past 24 hours, assuming this script runs once a way
DIRS=`${FIND} ${CERT_SRC} -mtime 1 -type d -d 1`
for dir in ${DIRS}
do
	echo ${dir}
	
	cert=`${BASENAME} ${dir}`
	echo ${cert}
	
	STAGING_USED=`${SYSRC} -nf ${cert}/${cert}.conf Le_API | grep staging`
	if [ ! ${STAGING_USED} ]; then
		# this is not staging
		${MKDIR} ${TMP}/${cert}
	
		${CP} -a ${CERT_SRC}/${cert}/${cert}.cer   ${TMP}/${cert}/
		${CP} -a ${CERT_SRC}/${cert}/ca.cer        ${TMP}/${cert}/
		${CP} -a ${CERT_SRC}/${cert}/fullchain.cer ${TMP}/${cert}/${cert}.fullchain.cer

		# if the destination directory already exists, overwrite the contents and remove the directory
		# we just created	
		if [ -d ${CERT_DST_ROOT}/${cert} ]; then
			${MV} ${TMP}/${cert}/* ${CERT_DST_ROOT}/${cert}/
			${RMDIR} ${TMP}/${cert}
		else
			# otherwise, move what we just created into the destination
			# we prefer mv over cp to avoid race conditions.
			${MV} ${TMP}/${cert} ${CERT_DST_CERTS}/
		fi
	fi
done
